version: '3.9'
services:
    app:
        image: getting-started-app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        ports:
            - '3000:3000'
